### ISSUE TITLE
Need to release a new version

### ISSUE THREAD

**Issue by chengluyu** [taichi-dev/taichi_glsl#8]
The latest version (0.0.8) doesn't work because this line is not included in the release. https://github.com/taichi-dev/taichi_glsl/blob/bdff10becd33a808148eec3afc04db3a5819a062/taichi_glsl/lagrangian.py#L6

This affects examples (e.g. [mass_spring_3d](https://github.com/taichi-dev/taichi/blob/master/examples/mass_spring_3d.py)). Following error will be raised. Maybe we should release a new version? 🤔

```
[Taichi] mode=release
[Taichi] preparing sandbox at /var/folders/59/8w1k63jj0vs_rv19jwyf1nf00000gn/T/taichi-f1cw8gi3
[Taichi] version 0.6.29, llvm 10.0.0, commit f1bde29b, osx, python 3.8.5
[TaiGLSL] version 0.0.8
[TaiGLSL] Inputs are welcomed at https://github.com/taichi-dev/taichi_glsl
[Tai3D] version 0.0.3
[Taichi] Starting on arch=x64
[Taichi] materializing...
Traceback (most recent call last):
  File "references/mass_spring_2d.py", line 105, in <module>
    substep()
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi/lang/kernel.py", line 580, in wrapped
    return primal(*args, **kwargs)
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi/lang/kernel.py", line 507, in __call__
    self.materialize(key=key, args=args, arg_features=arg_features)
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi/lang/kernel.py", line 378, in materialize
    taichi_kernel = taichi_kernel.define(taichi_ast_generator)
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi/lang/kernel.py", line 375, in taichi_ast_generator
    compiled()
  File "references/mass_spring_2d.py", line 52, in substep
    v[i] = tl.ballBoundReflect(x[i], v[i], tl.vec(+0.0, +0.2, -0.0), 0.4,
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi/lang/kernel.py", line 42, in decorated
    return fun.__call__(*args)
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi/lang/kernel.py", line 87, in __call__
    ret = self.compiled(*args)
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi_glsl/lagrangian.py", line 43, in ballBoundReflect
    above = tl.distance(pos, center) - radius
NameError: name 'tl' is not defined
```

**Comment by archibate** [comment]
Sorry for the trouble! Released (`v0.0.9`)[https://github.com/taichi-dev/taichi_glsl/releases/tag/v0.0.9] just now.

**Comment by chengluyu** [comment]
🙌 Thanks for you guys work. But I find the [mass_spring_3d](https://github.com/taichi-dev/taichi/blob/master/examples/mass_spring_3d.py) doesn't work after upgrade because of another error. I think this may caused by API mismatch between taichi_glsl 0.0.9 and taichi_three 0.0.3? 🤔

```
[Taichi] mode=release
[Taichi] preparing sandbox at /var/folders/59/8w1k63jj0vs_rv19jwyf1nf00000gn/T/taichi-bre18y_j
[Taichi] version 0.6.29, llvm 10.0.0, commit f1bde29b, osx, python 3.8.5
[TaiGLSL] version 0.0.9
[TaiGLSL] Inputs are welcomed at https://github.com/taichi-dev/taichi_glsl
[Tai3D] version 0.0.3
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "mass_spring_2d.py", line 62, in <module>
    model = t3.Model(f_n=(N - 1)**2 * 4, vi_n=N**2, vt_n=N**2, f_m=1)
  File "/Users/[REDACTED]/venv/lib/python3.8/site-packages/taichi_three/model.py", line 15, in __init__
    self.L2W = Affine.var(())
AttributeError: type object 'Affine' has no attribute 'var'
```

**Comment by archibate** [comment]
Oh I see, just pushed a commit to `taichi_three` which should solve the problem.

**Comment by chengluyu** [comment]
Thanks. I've try the change locally. 🎉 It works. I'm closing this now.
